#!/usr/bin/env python3
"""Rulepack expander.

Reads:
  rulepacks/cwe/*.yml          - CWE rule files
  rulepacks/infra/*.yml        - infrastructure rules
  rulepacks/frameworks/*.yml   - framework source/sink fragments
  rulepacks/languages/*.yml    - language-base source/sink fragments

For each rule that lists ``framework_sources: [name, ...]`` or
``language_sources: [name, ...]``, looks up the named pack and inlines
its source patterns into the rule's ``pattern-sources`` block.

Writes:
  rulepacks/_expanded/<original-relative-path>

The expanded directory is what OpenGrep consumes via ``--config``. Source
YAML stays DRY; expansion is a deterministic build step.

Usage:
    python expand_rulepacks.py
    python expand_rulepacks.py --check    # exit 1 if expanded is stale
"""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path
from typing import Any

import yaml


class _NoAliasDumper(yaml.SafeDumper):
    """SafeDumper that never emits YAML aliases.

    OpenGrep's rule loader doesn't expand `*anchor` references; rules
    expanded with shared subtrees (multiple rules referencing the
    same framework pack) end up with `pattern-sources: *id001` and
    fail validation. Deep-copy + alias-disabled dumping keeps each
    rule's sources structurally independent.
    """

    def ignore_aliases(self, data: Any) -> bool:  # noqa: D401, ARG002
        return True

REPO_ROOT_MARKER = "pyproject.toml"


def find_scanner_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / REPO_ROOT_MARKER).exists():
            return parent
    raise SystemExit(f"could not find scanner root from {here}")


def load_yaml(path: Path) -> Any:
    with path.open("rb") as fh:
        return yaml.safe_load(fh)


def dump_yaml(path: Path, doc: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write(
            f"# AUTO-GENERATED by scripts/expand_rulepacks.py. Do not edit.\n"
        )
        yaml.dump(
            doc, fh, Dumper=_NoAliasDumper,
            sort_keys=False, allow_unicode=True,
        )


def load_source_packs(packs_dir: Path) -> dict[str, list[Any]]:
    """Read framework / language packs into a lookup keyed by pack name.

    Pack files use a Deva-specific schema (NOT a Semgrep rules file):

        framework: spring          # or `language: java-base`
        languages: [java]
        sources:
          - patterns: [...]        # standard Semgrep pattern-sources entries
    """
    packs: dict[str, list[Any]] = {}
    if not packs_dir.exists():
        return packs
    for path in sorted(packs_dir.glob("*.yml")):
        doc = load_yaml(path) or {}
        if not isinstance(doc, dict):
            continue
        name = doc.get("framework") or doc.get("language") or path.stem
        sources = doc.get("sources") or []
        if not isinstance(sources, list):
            continue
        packs[str(name)] = sources
    return packs


def expand_rule(
    rule: dict[str, Any],
    framework_packs: dict[str, list[Any]],
    language_packs: dict[str, list[Any]],
) -> dict[str, Any]:
    out = dict(rule)
    fs_refs = out.pop("framework_sources", None) or []
    ls_refs = out.pop("language_sources", None) or []

    if not fs_refs and not ls_refs:
        return out

    inlined: list[Any] = []
    for ref in fs_refs:
        if ref not in framework_packs:
            raise SystemExit(
                f"rule {rule.get('id')!r}: unknown framework_sources "
                f"reference {ref!r}. Known: {sorted(framework_packs)}"
            )
        # Deep-copy so each rule gets its own subtree -- prevents the
        # YAML dumper from emitting `*anchor` aliases that OpenGrep
        # can't follow.
        inlined.extend(copy.deepcopy(framework_packs[ref]))
    for ref in ls_refs:
        if ref not in language_packs:
            raise SystemExit(
                f"rule {rule.get('id')!r}: unknown language_sources "
                f"reference {ref!r}. Known: {sorted(language_packs)}"
            )
        inlined.extend(copy.deepcopy(language_packs[ref]))

    existing = out.get("pattern-sources") or []
    if not isinstance(existing, list):
        existing = []
    out["pattern-sources"] = list(existing) + inlined
    return out


def expand_file(
    src: Path,
    dest: Path,
    framework_packs: dict[str, list[Any]],
    language_packs: dict[str, list[Any]],
) -> None:
    doc = load_yaml(src) or {}
    rules = doc.get("rules")
    if not isinstance(rules, list):
        # Not a rules file (e.g., a framework pack). Skip.
        return
    expanded = [expand_rule(r, framework_packs, language_packs) for r in rules]
    dump_yaml(dest, {"rules": expanded})


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any expanded file would change",
    )
    ap.add_argument(
        "--skip-validate",
        action="store_true",
        help=(
            "skip the OpenGrep parse-validation step. Off by default; "
            "useful for fast iteration when you know you're going to "
            "fix the rule before scanning."
        ),
    )
    args = ap.parse_args()

    root = find_scanner_root()
    rulepacks = root / "rulepacks"
    expanded_root = rulepacks / "_expanded"

    framework_packs = load_source_packs(rulepacks / "frameworks")
    language_packs = load_source_packs(rulepacks / "languages")

    drift: list[Path] = []
    if not args.check and expanded_root.exists():
        # Wipe stale output so deletions in source propagate.
        for stale in expanded_root.rglob("*.yml"):
            stale.unlink()

    sources = []
    for sub in ("cwe", "infra"):
        d = rulepacks / sub
        if d.exists():
            sources.extend(sorted(d.glob("*.yml")))

    written = 0
    for src in sources:
        rel = src.relative_to(rulepacks)
        dest = expanded_root / rel
        if args.check:
            current = dest.read_text(encoding="utf-8") if dest.exists() else None
            buf = _expand_to_string(src, framework_packs, language_packs)
            if buf is None:
                continue
            if current != buf:
                drift.append(rel)
            else:
                written += 1
        else:
            expand_file(src, dest, framework_packs, language_packs)
            written += 1

    if args.check and drift:
        print("Expanded rulepack is stale:", file=sys.stderr)
        for p in drift:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(
        f"expanded {written} rule file(s) "
        f"({len(framework_packs)} framework pack(s), "
        f"{len(language_packs)} language pack(s))"
    )

    # Validate the expanded rulepack actually loads in OpenGrep. A
    # rule that parses as YAML but contains a pattern OpenGrep can't
    # parse (e.g. a bare PHP `echo $X` without semicolon) only blows
    # up at scan time -- by which point the engine has already
    # discarded all findings from the run. Catching that here keeps
    # bad rules from shipping.
    if not args.skip_validate:
        rc = _validate_with_opengrep(root, expanded_root)
        if rc != 0:
            return rc

    return 0


def _validate_with_opengrep(scanner_root: Path, expanded_root: Path) -> int:
    """Run `opengrep validate` over the expanded tree.

    Returns 0 if every rule parses, non-zero if any rule fails parse.
    Skipped quietly (with a note) if the bundled OpenGrep binary is
    not where we expect it -- we don't want this to break local
    workflows that vendor OpenGrep elsewhere.
    """
    candidates = [
        scanner_root / "vendor" / "opengrep" / "bin" / "opengrep",
        Path(shutil_which("opengrep") or ""),
    ]
    bin_path = next(
        (p for p in candidates if p and p.exists()),
        None,
    )
    if bin_path is None:
        print(
            "validate: opengrep binary not found; skipping validation. "
            "Install or vendor it at vendor/opengrep/bin/opengrep to "
            "enable this check.",
            file=sys.stderr,
        )
        return 0

    import subprocess
    proc = subprocess.run(
        [str(bin_path), "validate", str(expanded_root)],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        print(
            "validate: opengrep rejected the expanded rulepack:",
            file=sys.stderr,
        )
        print(proc.stderr.strip() or proc.stdout.strip(), file=sys.stderr)
        return proc.returncode
    print(f"validate: ok ({len(list(expanded_root.rglob('*.yml')))} files)")
    return 0


def shutil_which(name: str) -> str | None:
    import shutil
    return shutil.which(name)


def _expand_to_string(
    src: Path,
    framework_packs: dict[str, list[Any]],
    language_packs: dict[str, list[Any]],
) -> str | None:
    doc = load_yaml(src) or {}
    rules = doc.get("rules")
    if not isinstance(rules, list):
        return None
    expanded = [expand_rule(r, framework_packs, language_packs) for r in rules]
    import io

    buf = io.StringIO()
    buf.write(
        "# AUTO-GENERATED by scripts/expand_rulepacks.py. Do not edit.\n"
    )
    yaml.dump(
        {"rules": expanded}, buf, Dumper=_NoAliasDumper,
        sort_keys=False, allow_unicode=True,
    )
    return buf.getvalue()


if __name__ == "__main__":
    sys.exit(main())
