"""Tests for the data-file filter in the quality layer.

The filter drops findings under documentation, lockfile, generated,
and project-metadata paths because rules looking for code-like
signals (PII, secret shapes, password assignments) reliably misfire
there.

The line we draw matters more than for the test-file filter:
infrastructure-as-code files (Dockerfile, *.tf, *.yaml) and real
credential surfaces (.env) must NOT be filtered. The fixtures below
exercise both sides.
"""
from __future__ import annotations

import pytest

from dsc.scanner.models import Finding, Severity
from dsc.scanner.quality import (
    FULL_BALANCED,
    apply_quality_layer,
    is_data_path,
)


def _finding(*, file_path: str, metadata: dict | None = None) -> Finding:
    meta = {
        "fingerprint": f"fp-{file_path}",
        "occurrence_id": f"occ-{file_path}",
        "precision_tier": "A",
        "confidence": 0.95,
        "family": "secrets",
    }
    if metadata:
        meta.update(metadata)
    return Finding(
        rule_id="deva.cwe-359.pii-network-or-device",
        cwe="CWE-359",
        severity=Severity.MEDIUM,
        file_path=file_path,
        line_start=10,
        line_end=10,
        column=1,
        message="possible PII",
        snippet="match",
        metadata=meta,
    )


# ───── inclusion (these ARE data files) ────────────────────────────────────


@pytest.mark.parametrize(
    "path",
    [
        # Documentation
        "README.md",
        "docs/architecture.md",
        "docs/zh-CN/gateway/configuration.md",
        "docs/api.mdx",
        "guide.rst",
        "guide.adoc",
        # Lockfiles
        "package-lock.json",
        "src/web/package-lock.json",
        "npm-shrinkwrap.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "Pipfile.lock",
        "poetry.lock",
        "Gemfile.lock",
        "Cargo.lock",
        "composer.lock",
        "go.sum",
        "flake.lock",
        # Generated by naming convention
        "src/schema.base.generated.ts",
        "src/types.gen.ts",
        "src/types-generated.ts",
        "rpc/service.pb.go",
        "rpc/service.pb.ts",
        "src/foo.codegen.js",
        # Jest snapshots
        "__snapshots__/UserCard.test.ts.snap",
        "src/foo.test.ts.snap",
        # Git / project metadata
        ".gitignore",
        ".gitattributes",
        ".mailmap",
        ".editorconfig",
        "CODEOWNERS",
        ".github/CODEOWNERS",
        # Security baselines (the user's specific case)
        ".secrets.baseline",
        ".detect-secrets.cfg",
        ".semgrepignore",
        # Bulk data
        "docs/.i18n/zh-CN.tm.jsonl",
        "data/users.csv",
        "fixtures/payload.ndjson",
        "samples/big.tsv",
        # i18n
        "locales/en/messages.po",
        "i18n/zh-CN/strings.po",
        "translations/de.pot",
        # Windows paths
        r"docs\architecture.md",
        r"src\schema.generated.ts",
    ],
)
def test_is_data_path_true(path: str) -> None:
    assert is_data_path(path), f"expected {path!r} to be a data path"


# ───── exclusion (these are NOT data files; rules must still apply) ────────


@pytest.mark.parametrize(
    "path",
    [
        # Production source
        "src/auth.ts",
        "src/payments.py",
        # IaC / infrastructure code — real rules apply here
        "Dockerfile",
        "infra/Dockerfile",
        "deploy/k8s.yaml",
        "deploy/service.yml",
        ".github/workflows/ci.yml",
        "terraform/main.tf",
        # Real credential surfaces — must still scan
        ".env",
        ".env.local",
        ".env.production",
        # Regular JSON config (could carry secrets; don't blanket-skip)
        "config/server.json",
        "tsconfig.json",
        "package.json",  # NOT package-lock.json
        # Markdown-adjacent but actually code
        "src/markdown_renderer.ts",
        # Empty / weird
        "",
        "/",
    ],
)
def test_is_data_path_false(path: str) -> None:
    assert not is_data_path(path), f"expected {path!r} NOT to be a data path"


# ───── apply_quality_layer integration ─────────────────────────────────────


def test_findings_in_data_files_are_dropped() -> None:
    prod = _finding(file_path="/ws/src/auth.ts")
    doc = _finding(file_path="/ws/README.md")
    lock = _finding(file_path="/ws/package-lock.json")
    baseline = _finding(file_path="/ws/.secrets.baseline")
    generated = _finding(file_path="/ws/src/schema.generated.ts")
    iac = _finding(file_path="/ws/Dockerfile")  # NOT filtered

    out = apply_quality_layer(
        [prod, doc, lock, baseline, generated, iac],
        detectors={},
        target_root="/ws",
        policy=FULL_BALANCED,
        suppressions={},
    )
    paths = sorted(o.file_path for o in out)
    assert paths == ["/ws/Dockerfile", "/ws/src/auth.ts"]


def test_per_rule_opt_in_keeps_data_file_findings() -> None:
    """A rule that opts in survives the filter -- e.g., a future
    'secret committed in a CHANGELOG.md' rule.
    """
    doc_finding = _finding(
        file_path="/ws/CHANGELOG.md",
        metadata={"apply_to_data_files": True},
    )
    out = apply_quality_layer(
        [doc_finding],
        detectors={},
        target_root="/ws",
        policy=FULL_BALANCED,
        suppressions={},
    )
    assert len(out) == 1


def test_env_opt_out_keeps_data_findings(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """DSC_INCLUDE_DATA_FINDINGS=1 disables the filter entirely."""
    monkeypatch.setenv("DSC_INCLUDE_DATA_FINDINGS", "1")
    out = apply_quality_layer(
        [_finding(file_path="/ws/README.md")],
        detectors={},
        target_root="/ws",
        policy=FULL_BALANCED,
        suppressions={},
    )
    assert len(out) == 1


def test_all_three_filters_compose() -> None:
    """The three filters (allowlist, test-file, data-file) run in
    sequence on the same stream. Each should fire independently.
    """
    prod_kept = _finding(file_path="/ws/src/auth.ts")
    test_dropped = _finding(file_path="/ws/src/auth.test.ts")
    doc_dropped = _finding(file_path="/ws/README.md")
    pragma_dropped = Finding(
        rule_id="deva.cwe-798.private-key-header",
        cwe="CWE-798",
        severity=Severity.CRITICAL,
        file_path="/ws/src/keys.ts",
        line_start=5,
        line_end=5,
        column=1,
        message="key detected",
        snippet='"BEGIN PRIVATE KEY" // pragma: allowlist secret',
        metadata={
            "fingerprint": "fp-pragma",
            "occurrence_id": "occ-pragma",
            "precision_tier": "A",
            "confidence": 0.95,
        },
    )
    out = apply_quality_layer(
        [prod_kept, test_dropped, doc_dropped, pragma_dropped],
        detectors={},
        target_root="/ws",
        policy=FULL_BALANCED,
        suppressions={},
    )
    paths = [o.file_path for o in out]
    assert paths == ["/ws/src/auth.ts"]


def test_user_specific_detect_secrets_cfg_case() -> None:
    """Regression: the openclaw .detect-secrets.cfg false positive that
    survived items #1 and #2 must be dropped by item #3.
    """
    f = _finding(file_path="/ws/.detect-secrets.cfg")
    out = apply_quality_layer(
        [f],
        detectors={},
        target_root="/ws",
        policy=FULL_BALANCED,
        suppressions={},
    )
    assert out == []
